name: Pull Request Build, Push and Deploy

on:
  # Execute on every pull request to the master branch
  pull_request_target:
    branches:
      - master

jobs:
  mqtt-detection-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Turnstyle ensures that this job only runs one at a time in this repository
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: call-for-code/build-push-deploy@main
        with:
          cloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
          cloud-resource-group: OpenEEW-Infra
          cloud-region: us-south
          deployment-name: openeew-detection-mqtt-test
          github-sha: ${{ github.sha }}
          icr-namespace: ${{ secrets.ICR_NAMESPACE }}
          image-name: detection-mqtt-gha
          k8s-cluster-name: ${{ secrets.K8S_CLUSTER_NAME }}
          k8s-cluster-namespace: ${{ secrets.K8S_CLUSTER_NAMESPACE }}
          registry-hostname: us.icr.io

  db-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Turnstyle ensures that this job only runs one at a time in this repository
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: call-for-code/build-push-deploy@main
        with:
          cloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
          cloud-resource-group: OpenEEW-Infra
          cloud-region: us-south
          deployment-name: openeew-detection-db-test
          github-sha: ${{ github.sha }}
          icr-namespace: ${{ secrets.ICR_NAMESPACE }}
          image-name: detection-db-gha
          k8s-cluster-name: ${{ secrets.K8S_CLUSTER_NAME }}
          k8s-cluster-namespace: ${{ secrets.K8S_CLUSTER_NAMESPACE }}
          registry-hostname: us.icr.io
          working-directory: "database/"
